package com.revature.project2.Controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import com.revature.project2.Repositories.CartsRepository;
import com.revature.project2.Entities.Carts;


@Controller    // This means that this class is a Controller
@RequestMapping(path="/Carts") // This means URL's start with /demo (after Application path)
public class CartsController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private CartsRepository cartRepository;

	@PostMapping(path="/add") // Map ONLY POST Requests
	public @ResponseBody String addNewUser (@RequestParam double cost
			) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Carts new_cart = new Carts();
		//new_dart.setId(id);;
        new_cart.setCost(cost);

		cartRepository.save(new_cart);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<Carts> getAllUsers() {
		// This returns a JSON or XML with the users
		return cartRepository.findAll();
	}
}