package com.revature.project2.Controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import com.revature.project2.Repositories.UsersRepository;
import com.revature.project2.Entities.Users;


@Controller    // This means that this class is a Controller
@RequestMapping(path="/Users") // This means URL's start with /demo (after Application path)
public class UsersController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private UsersRepository userRepository;

	@PostMapping(path="/add") // Map ONLY POST Requests
	public @ResponseBody String addNewUser (@RequestParam String first 
			, @RequestParam String last, @RequestParam String usr, @RequestParam String psw
			, @RequestParam String address, @RequestParam String city, @RequestParam String state
			, @RequestParam String zip, @RequestParam int age) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Users new_user = new Users();
		//new_user.setId(id);;
		new_user.setFirst(first);
		new_user.setLast(last);
		new_user.setUsername(usr);
		new_user.setPsw(psw);
		new_user.setAddress(address);
		new_user.setCity(city);
		new_user.setState(state);
		new_user.setZipcode(zip);
		new_user.setAge(age);

		userRepository.save(new_user);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<Users> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}
}